services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "Sh@shank9868b"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - global-network

  pgadmin4:
    image: elestio/pgadmin
    container_name: pgadmin-panel
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: shashank.singh2016.ss@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "Sh@shank9868b"
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - global-network

volumes:
  pgdata:
  pgadmin_data:

networks:
  global-network:
    external: true