services:
  portfolio-1: 
    build: .
    environment: 
      - APP_NAME=portfolio-1
    ports:
      - "3001:3000"
    networks:
      - global-network

  portfolio-2: 
    build: .
    environment: 
      - APP_NAME=portfolio-2
    ports:
      - "3002:3000"
    networks:
      - global-network

  portfolio-3: 
    build: .
    environment: 
      - APP_NAME=portfolio-3
    ports:
      - "3003:3000"
    networks:
      - global-network

networks:
  global-network:
    external: true